package:
  name: libxml2-static
  version: 2.9.3

source:
  fn: libxml2-2.9.3.tar.gz
  url: http://xmlsoft.org/sources/libxml2-2.9.3.tar.gz
  md5: daece17e045f1c107610e137ab50c179

build:
  number: 5

requirements:
  build:
    - {{ compiler('c') }}
about:
  home: http://www.xmlsoft.org/
  summary: The XML C parser and toolkit of Gnome
