name: tigl-bld
# This is the recommended environment for building tigl from source
channels:
 - dlr-sc
 - dlr-sc/label/tigl-dev
dependencies:
 - pip                           # just make sure that pip installs into this env, if used
 # required build dependencies
 - opencascade=7.6.2             # library for dealing with b-spline and nurbs geometries. dlr-sc version contains patch for C2-cont. Coons patches
 - tixi3=3.3.1                   # library for dealing with xml files
 # optional dependencies
 - conda-forge::qt=5.15.15       # needed to build tiglcreator
 - doxygen=1.8.15                # needed to build the documenation
 - python<=3.12                  # needed to build python bindings
 - swig>=3.0.11                  # needed to build python bindings
 - pythonocc-core=7.6.2          # needed to build python bindings
 - matlab-libs                   # needed to build matlab bindings
 # other build dependencies
 - ninja>=1.10.0                 # not strictly needed, tigl can be build using any other camke generator
 - freeimageplus                 # used by opencascade
 - brotlipy                      # Workaround for issue on windows, see: https://github.com/conda/conda/issues/9903#issuecomment-647091019
