/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class tigl_android_test_2 */

#ifndef _Included_tigl_android_test_2
#define _Included_tigl_android_test_2
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     tigl_android_test_2
 * Method:    result
 * Signature: (DD)D
 */
JNIEXPORT jdouble JNICALL Java_tigl_android_test_2_result
  (JNIEnv *, jobject, jdouble, jdouble);

#ifdef __cplusplus
}
#endif
#endif
