name: "MacOS Tests"

description: "Test TiGL on MacOS"

inputs:

  build-artifact:
    description: "Name of the build artifact that contains the unit test binary."
    required: true

  unit-tests:
    description: "Set to true to run TiGLs unit tests (true or false)"
    required: false
    default: true

  integration-tests:
    description: "Set to true to run TiGLs integration tests (true or false)"
    required: false
    default: true

runs:

  using: "composite"
  
  steps:
  
    - name: Setup miniconda
      uses: conda-incubator/setup-miniconda@v2
      with:
        auto-update-conda: true
        auto-activate-base: true
        activate-environment: ''
        python-version: "3.8"

    - name: Install tixi and pythonocc-core from conda
      shell: bash -l {0}
      run: |
        conda install tixi3=3.3.0 pythonocc-core=7.4.1 -c dlr-sc -c dlr-sc/label/tigl-dev

    - name: Download built test directory
      uses: actions/download-artifact@v3
      with:
        name: ${{ inputs.build-artifact }}

    - name: extract build archive
      shell: bash
      run: |
        tar -xzf build.tar.gz

    - name: Run unit tests
      if: ${{ inputs.unit-tests == 'true' }}
      shell: bash
      run: |
        cd build/tests/unittests/
        chmod a+x ./TiGL-unittests
        ./TiGL-unittests --gtest_shuffle --gtest_output=xml:unit_test_results.xml

    - name: Run integration tests
      if: ${{ inputs.integration-tests == 'true' }}
      shell: bash
      run: |
        cd build/tests/integrationtests/
        chmod a+x ./TiGL-integrationtests
        ./TiGL-integrationtests --gtest_shuffle --gtest_output=xml:integration_test_results.xml
