{% set version = "0.17.2" %}

package:
  name: oce-static
  version: {{ version }}

source:
  fn: OCE-{{ version }}.tar.gz
  url: https://github.com/tpaviot/oce/archive/OCE-{{ version }}.tar.gz
  patches:
    - fix_tkopengl_dll_path.patch     # [win]
    - dlr-feature-coons_c2.patch
    - fix-tiglviewer-selection.patch
    - oceonly-freeimage_staticlib_support.patch
    - fix-freetype26-fonts.patch
    - glibc.patch                     # [linux]

build:
  detect_binary_files_with_prefix: True
  number: 4
  features:
    - vc9              # [win and py27]
    - vc10             # [win and py34]
    - vc14             # [win and py35]

requirements:
  build:
    - patch            # [win]
    - python
    - freetype-static ==2.6
    - freeimageplus-static ==3.17.0
    - ninja ==1.7.1
    - cmake
    - gcc              # [linux]


about:
  home: https://github.com/tpaviot/oce
  license: LGPL
  summary: OpenCASCADE community edition
