//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by TIGLViewer.rc
//
#define IDP_OLE_INIT_FAILED             100
#define IDR_MAINFRAME                   128
#define IDD_ABOUTBOX                    600
#define IDR_TIGLCHILDFRAME              629
#define IDD_WING_PROFILE_DIALOG         631
#define IDD_WING_DIALOG                 632
#define IDD_FUSELAGE_PROFILE_DIALOG     633
#define IDD_FUSELAGE_DIALOG             634
#define IDD_CONFIGURATION_DIALOG        635
#define IDC_WING_PROFILE_LIST           2000
#define IDC_WING_LIST                   2001
#define IDC_FUSELAGE_GROUP_TEXT         2004
#define IDC_FUSELAGE_PROFILE_LIST       2005
#define IDC_WING_GROUP_TEXT             2006
#define IDC_FUSELAGE_LIST               2007
#define IDC_CONFIGURATION_LIST          2008
#define ID_SHOW_ALL                     50771
#define ID_INTERPOLATE_BSPLINE_WIRE     50787
#define ID_INTERPOLATE_LINEAR_WIRE      50788
#define ID_APPROXIMATE_BSPLINE_WIRE     50789
#define ID_SHOW_WINGS                   50791
#define ID_SHOW_WING_POINTS             50794
#define ID_SHOW_WING_MESHES             50797
#define ID_SHOW_WING_TRIANGULATION      50798
#define ID_SHOW_ALL_POINTS              50801
#define ID_DATEI_EXPORTASIGES           50803
#define ID_EXPORT_AS_IGES               50804
#define ID_SHOW_WING_PROFILES           50806
#define ID_SHOW_FUSELAGE_PROFILES       50808
#define ID_SHOW_FUSELAGES               50810
#define ID_SHOW_FUSELAGE_TRIANGULATION  50812
#define ID_SHOW_FUSELAGE_POINTS         50814
#define ID_CPACS_DRAWFUSEDWINGS         50822
#define ID_CPACS_DRAWFUSEDFUSELAGES     50823
#define ID_CPACS_SHOWINTERSECTIONLINE   50825
#define ID_EXPORT_FUSED_IGES            50829
#define ID_CPACS_DRAWFUSEDALL           50832
#define ID_EXPORT_MESHED_WING_STL       50835
#define ID_EXPORT_MESHED_VTK            50837
#define ID_EXPORTASSTL_WINGBYINDEX      50843
#define ID_EXPORTASSTL_WINGBYUID        50844
#define ID_EXPORTASSTL_FUSELAGEBYINDEX  50845
#define ID_EXPORTASSTL_FUSELAGEBYUID    50846
#define ID_EXPORTASSTL_COMPLETEGEOMETRY 50847
#define ID_EXPORTASVTK_WINGBYINDEX      50848
#define ID_EXPORTASVTK_FUSELAGEBYINDEX  50849
#define ID_EXPORTASVTK_FUSELAGEBYUID    50850
#define ID_EXPORTASVTK_COMPLETEGEOMETRY 50852
#define ID_SHOW_FUSELAGE_POINTS_ANGLE   50854
#define ID_CPACS_DRAWOVERLAYCPACSPROFILEPOINTS 50855
#define ID_EXPORTASVTK_WINGBYUID        50856
#define ID_CPACS_DRAW_MINIMUM_DISTANCE_GROUND 50858

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        636
#define _APS_NEXT_COMMAND_VALUE         50859
#define _APS_NEXT_CONTROL_VALUE         2008
#define _APS_NEXT_SYMED_VALUE           206
#endif
#endif
