{% set version = "3.0.3" %}

package:
  name: tixi3
  version: {{ version }}

source:
  fn: tixi-{{ version }}.tar.gz
  url: https://github.com/DLR-SC/tixi/archive/v{{ version }}.tar.gz
  md5: 62befb444108b6db6e89b7ebd865b5a7
  patches:
    - fixvs2008.patch

build:
  number: 0

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - patch             # [win]
    - doxygen =1.8.10

  host:
    - python {{ python }}
    - curl-static ==7.50.3
    - libxml2-static ==2.9.3
    - libxslt-static ==1.1.29

  run:
    - python

test:
    commands:
    - tixiDemo

about:
  home: https://github.com/DLR-SC/tixi
  license: Apache 2.0
  summary: Fast and simple XML interface library
