# This is a makefile to build the example TiGL program

# Please modify the variables TIGL_HOME and TIXI_HOME 
# to the appropriate install locations
TIGL_HOME=<tigl install folder>
TIXI_HOME=<tixi install folder>

c-demo.exe: c-demo.c
	cl.exe /nologo c-demo.c -I $(TIGL_HOME)\include -I $(TIXI_HOME)\include $(TIGL_HOME)\lib\TIGL.lib $(TIXI_HOME)\lib\TIXI.lib 