package:
  name: ninja
  version: 1.8.2

source:
  fn: ninja-1.8.2.tar.gz
  url: https://github.com/ninja-build/ninja/archive/v1.8.2.tar.gz

build:
  number: 0

requirements:
  build:
    - {{ compiler('cxx') }}
    - python

about:
  home: https://ninja-build.org/
  summary: A small build system with a focus on speed.
