mkdir build
cd build

# Configure step
cmake -G "Ninja" -DCMAKE_INSTALL_PREFIX=$PREFIX \
 -DCMAKE_C_FLAGS=-fPIC -DCMAKE_CXX_FLAGS=-fPIC \
 -DCMAKE_BUILD_TYPE=Release \
 -DOCE_TESTING=OFF \
 -DOCE_BUILD_SHARED_LIB=OFF \
 -DCMAKE_PREFIX_PATH=$PREFIX \
 -DCMAKE_SYSTEM_PREFIX_PATH=$PREFIX \
 -DOCE_INSTALL_LIB_DIR=lib \
 -DOCE_INSTALL_BIN_DIR=bin \
 -DOCE_MULTITHREAD_LIBRARY=OPENMP \
 -DOCE_WITH_FREEIMAGE=ON \
 -DOCE_INSTALL_PREFIX=$PREFIX -DOCE_ENABLE_DEB_FLAG=OFF ..

# Build step
ninja

# Install step
ninja install

