package:
  name: freeimageplus-static
  version: 3.17.0

source:
  fn: new-bundle.zip [win]
  url: https://github.com/QbProg/oce-win-bundle/archive/qb/new-bundle.zip [win]
  fn: FreeImage3170.zip [unix]
  url: http://downloads.sourceforge.net/freeimage/FreeImage3170.zip [unix]
  patches:
    - installdir.patch   [win]
    - installlinux.patch [linux]

build:
  number: 2

requirements:
  build:
    - {{ compiler('cxx') }}
    - patch             [win]
    - cmake             [win]
    - ninja


about:
  home: http://freeimage.sourceforge.net/
  license: GNU LPGL Version 2 and FreeImage Public License
  summary: FreeImage, The productivity booster
