{% set version = "2.2.4" %}

package:
  name: tixi
  version: {{ version }}

source:
  fn: tixi-{{ version }}.tar.gz
  url: https://github.com/DLR-SC/tixi/archive/v{{ version }}.tar.gz
  patches:
    - install.patch
    - remove_hard_links.patch

build:
  number: 1
  features:
    - vc9              # [win and py27]
    - vc10             # [win and py34]
    - vc14             # [win and py35]

requirements:
  build:
    - python
    - doxygen ==1.8.10
    - curl-static ==7.50.3
    - libxml2-static ==2.9.3
    - libxslt-static ==1.1.29
    - gcc               # [linux]

  run:
    - python

test:
  requires:
    - python 2.7.*     # [win and py27]
    - python 3.4.*     # [win and py34]
    - python 3.5.*     # [win and py35]

  commands:
    - tixiDemo

about:
  home: https://github.com/DLR-SC/tixi
  license: Apache 2.0
  summary: Fast and simple XML interface library
