#ifndef TIGLLOGGERDEFINITIONS_H
#define TIGLLOGGERDEFINITIONS_H

static const char* const LogLevelStrings[] = {"ERR", "WRN", "INF", "DBG", "DBG1", "DBG2", "DBG3 ", "DBG4"};
enum TiglLogLevel {TILOG_ERROR, TILOG_WARNING, TILOG_INFO, TILOG_DEBUG, TILOG_DEBUG1, TILOG_DEBUG2, TILOG_DEBUG3, TILOG_DEBUG4};

#endif // TIGLLOGGERDEFINITIONS_H
