name: CI workflow for main branch

on:
  schedule:
    - cron: "40 2 * * *"
  push:
    branches:
      - 'master'
    tags:
      - v*
  workflow_dispatch:

env:
  TIGL_NIGHTLY: "ON"
  TIGL_CONCAT_GENERATED_FILES: "ON"

jobs:

  build-linux:
    strategy:
      matrix:
        config: ["Debug", "Release"]
        os: ["ubuntu-latest", "ubuntu-18.04"]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Set CMake options for release builds
        # no nightly builds and concatenation of generated files, if we push a new tag (i.e. new release)
        if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/v')
        run: |
          echo "TIGL_NIGHTLY=OFF" >> $GITHUB_ENV
          echo "TIGL_CONCAT_GENERATED_FILES=OFF" >> $GITHUB_ENV
      - uses: actions/checkout@v2
      - uses: ./.github/actions/build-linux
        with:
          config: ${{ matrix.config }}
          tigl_nightly: ${{ env.TIGL_NIGHTLY }}
          tigl_concat_generated_files: ${{ env.TIGL_CONCAT_GENERATED_FILES }}
          tigl_enable_coverage: "OFF"
          build-artifact: build-${{ matrix.os }}-${{ matrix.config }}-nightly-${{ env.TIGL_NIGHTLY }}-concat-${{ env.TIGL_CONCAT_GENERATED_FILES }}-cov-OFF


  test-linux:
    needs: build-linux
    strategy:
      matrix:
        config: ["Debug", "Release"]
        os: ["ubuntu-latest", "ubuntu-18.04"]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/actions/test-linux
        with:
          build-artifact: build-${{ matrix.os }}-${{ matrix.config }}-nightly-${{ env.TIGL_NIGHTLY }}-concat-${{ env.TIGL_CONCAT_GENERATED_FILES }}-cov-OFF
          coverage: false
          unit-tests: true
          integration-tests: true

  build-windows:
    strategy:
      matrix:
        config: ["Release"]
        os: ["windows-2016", "windows-2019"]
        include:
         - config: "Release"
           os: "windows-2019"
           oce_static_libs: "ON"
           tigl_bindings_python_internal: "ON"
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - name: Set CMake options for release builds
        # no nightly builds and concatenation of generated files, if we push a new tag (i.e. new release)
        if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/v')
        run: |
          echo "TIGL_NIGHTLY=OFF" >> $GITHUB_ENV
          echo "TIGL_CONCAT_GENERATED_FILES=OFF" >> $GITHUB_ENV
      - uses: ./.github/actions/build-win
        with:
          config: ${{ matrix.config }}
          tigl_nightly: ${{ env.TIGL_NIGHTLY }}
          tigl_concat_generated_files: ${{ env.TIGL_CONCAT_GENERATED_FILES }}
          tigl_enable_coverage: 'OFF'
          oce_static_libs: ${{ matrix.oce_static_libs || 'OFF' }}
          tigl_bindings_python_internal: ${{ matrix.tigl_bindings_python_internal || 'OFF' }}
          build-artifact: build-${{ matrix.os }}-${{ matrix.config }}-nightly-${{ env.TIGL_NIGHTLY }}-concat-${{ env.TIGL_CONCAT_GENERATED_FILES }}-cov-OFF-static-${{ matrix.oce_static_libs || 'OFF' }}-python-${{ matrix.tigl_bindings_python_internal || 'OFF' }}


  test-windows:
    needs: build-windows
    strategy:
      matrix:
        config: ["Release"]
        os: ["windows-2016", "windows-2019"]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/actions/test-win
        with:
          build-artifact: build-${{ matrix.os }}-${{ matrix.config }}-nightly-${{ env.TIGL_NIGHTLY }}-concat-${{ env.TIGL_CONCAT_GENERATED_FILES }}-cov-OFF-static-${{ matrix.oce_static_libs || 'OFF' }}-python-${{ matrix.tigl_bindings_python_internal || 'OFF' }}
          coverage: false
          unit-tests: true
          integration-tests: true

  deploy-windows:
    needs: test-windows
    runs-on: "windows-2019"
    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/actions/deploy-win
        with:
          build-artifact: build-windows-2019-Release-nightly-ON-concat-ON-cov-OFF-static-ON-python-ON
          documentation: true

  build-macos:
    runs-on: "macOS-10.15"
    steps:
      - uses: actions/checkout@v2
      - name: Set CMake options for release builds
        # no nightly builds and concatenation of generated files, if we push a new tag (i.e. new release)
        if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/v')
        run: |
          echo "TIGL_NIGHTLY=OFF" >> $GITHUB_ENV
          echo "TIGL_CONCAT_GENERATED_FILES=OFF" >> $GITHUB_ENV
      - uses: ./.github/actions/build-macos
        with:
          config: "Release"
          tigl_nightly: "ON"
          tigl_concat_generated_files: "ON"
          tigl_enable_coverage: 'OFF'
          build-artifact: build-macOS-10.15-Release-nightly-${{ env.TIGL_NIGHTLY }}-concat-${{ env.TIGL_CONCAT_GENERATED_FILES }}-cov-OFF-static-ON-python-OFF

  test-macos:
    needs: build-macos
    runs-on: "macOS-10.15"
    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/actions/test-macos
        with:
          build-artifact: build-macOS-10.15-Release-nightly-${{ env.TIGL_NIGHTLY }}-concat-${{ env.TIGL_CONCAT_GENERATED_FILES }}-cov-OFF-static-ON-python-OFF
          coverage: false
          unit-tests: true
          integration-tests: false

  deploy-macos:
    needs: test-macos
    runs-on: "macOS-10.15"
    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/actions/deploy-macos
        with:
          build-artifact: build-macOS-10.15-Release-nightly-${{ env.TIGL_NIGHTLY }}-concat-${{ env.TIGL_CONCAT_GENERATED_FILES }}-cov-OFF-static-ON-python-OFF
          documentation: false

  draft-release:
    if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/v')
    needs: ["deploy-macos", "deploy-windows", "test-linux"]
    runs-on: "ubuntu-latest"
    steps:
      - uses: ./.github/actions/release
