name: CI workflow for main branch

on:
  schedule:
    - cron: "40 2 * * *"
  push:
    branches:
      - '*'
    tags:
      - v*
  workflow_dispatch:

jobs:

  pre:
    # no nightly cmake flag and no concatenation of generated files for release builds
    runs-on: "ubuntu-latest"
    outputs:
      nightly: ${{ steps.set_flags.outputs.nightly }}
      concat: ${{ steps.set_flags.outputs.concat }}
    steps:
      - id: set_flags
        shell: bash
        run: |
          if [[ "${{ github.event_name == 'push' && startsWith(github.ref, 'refs/tags/v') }}" == "true" ]]; then
            echo "nightly=OFF" >> $GITHUB_OUTPUT
            echo "concat=OFF" >> $GITHUB_OUTPUT
          else
            echo "nightly=ON" >> $GITHUB_OUTPUT
            echo "concat=ON" >> $GITHUB_OUTPUT
          fi

  build:
    needs: pre
    strategy:
      matrix:
        config: ["Debug", "Release"]
        os: ["ubuntu-latest", "ubuntu-22.04"]
        tests: ["ON"]
        # only release builds on windows
        include:
          - config: "Release"
            os: "windows-latest"
          - config: "Release"
            os: "windows-2022"
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v5
      - uses: prefix-dev/setup-pixi@v0.9.0
        with:
          cache: true
          cache-write: ${{ github.event_name == 'push' && github.ref_name == 'main' }}
      - run: pixi run configure ${{ matrix.tests }} ${{ matrix.config }}
      - run: pixi run install




