name: Pull Request CI workflow

on:
  pull_request:
    types: [ assigned, opened, synchronize, reopened ]
  workflow_dispatch:

jobs:

  continuous-integration:
    uses: ./.github/workflows/continuous-integration.yml
