name: Pull Request CI workflow

on:
  pull_request:
  workflow_dispatch:

jobs:

  continuous-integration:
    needs: pre
    uses: ./.github/workflows/continuous-integration.yml

#  build-linux:
#    strategy:
#      matrix:
#        config: ["Debug", "Release"]
#        os: ["ubuntu-latest", "ubuntu-18.04"]
#        # only enable coverage for Debug build on latest ubuntu
#        include:
#          - config: "Debug"
#            os: "ubuntu-latest"
#            coverage: "ON"
#    runs-on: ${{ matrix.os }}
#    steps:
#      - uses: actions/checkout@v2
#      - uses: ./.github/actions/build-linux
#        with:
#          config: ${{ matrix.config }}
#          tigl_nightly: "ON"
#          tigl_concat_generated_files: "ON"
#          tigl_enable_coverage: ${{ matrix.coverage || 'OFF' }}
#          build-artifact: build-${{ matrix.os }}-${{ matrix.config }}-nightly-ON-concat-ON-cov-${{ matrix.coverage || 'OFF' }}


#  test-linux:
#    needs: build-linux
#    strategy:
#      matrix:
#        config: ["Debug", "Release"]
#        os: ["ubuntu-latest", "ubuntu-18.04"]
#        include:
#          - config: "Debug"
#            os: "ubuntu-latest"
#            coverage: "ON"
#            unit-tests: false
#            integration-tests: false
#    runs-on: ${{ matrix.os }}
#    steps:
#      - uses: actions/checkout@v2
#      - uses: ./.github/actions/test-linux
#        with:
#          build-artifact: build-${{ matrix.os }}-${{ matrix.config }}-nightly-ON-concat-ON-cov-${{ matrix.coverage || 'OFF' }}
#          coverage: ${{ matrix.coverage == 'ON' || false }}
#          unit-tests: ${{ matrix.unit-tests || false }}
#          integration-tests: ${{ matrix.integration-tests || false }}


#  build-windows:
#    strategy:
#      matrix:
#        config: ["Release"]
#        os: ["windows-2016", "windows-2019"]
#        include:
#         - config: "Release"
#           os: "windows-2019"
#           oce_static_libs: "ON"
#           tigl_bindings_python_internal: "ON"
#    runs-on: ${{ matrix.os }}
#    steps:
#      - uses: actions/checkout@v2
#      - uses: ./.github/actions/build-win
#        with:
#          config: ${{ matrix.config }}
#          tigl_nightly: "ON"
#          tigl_concat_generated_files: "ON"
#          tigl_enable_coverage: 'OFF'
#          oce_static_libs: ${{ matrix.oce_static_libs || 'OFF' }}
#          tigl_bindings_python_internal: ${{ matrix.tigl_bindings_python_internal || 'OFF' }}
#          build-artifact: build-${{ matrix.os }}-${{ matrix.config }}-nightly-ON-concat-ON-cov-OFF-static-${{ matrix.oce_static_libs || 'OFF' }}-python-${{ matrix.tigl_bindings_python_internal || 'OFF' }}


#  test-windows:
#    needs: build-windows
#    strategy:
#      matrix:
#        config: ["Release"]
#        os: ["windows-2016", "windows-2019"]
#        include:
#         - config: "Release"
#           os: "windows-2019"
#           oce_static_libs: "ON"
#           tigl_bindings_python_internal: "ON"
#    runs-on: ${{ matrix.os }}
#    steps:
#      - uses: actions/checkout@v2
#      - uses: ./.github/actions/test-win
#        with:
#          build-artifact: build-${{ matrix.os }}-${{ matrix.config }}-nightly-ON-concat-ON-cov-OFF-static-${{ matrix.oce_static_libs || 'OFF' }}-python-${{ matrix.tigl_bindings_python_internal || 'OFF' }}
#          coverage: false
#          unit-tests: true
#          integration-tests: false

#  deploy-windows:
#    needs: test-windows
#    runs-on: "windows-2019"
#    steps:
#      - uses: actions/checkout@v2
#      - uses: ./.github/actions/deploy-win
#        with:
#          build-artifact: build-windows-2019-Release-nightly-ON-concat-ON-cov-OFF-static-ON-python-ON
#          documentation: false


#  build-macos:
#    runs-on: "macOS-10.15"
#    steps:
#      - uses: actions/checkout@v2
#      - uses: ./.github/actions/build-macos
#        with:
#          config: "Release"
#          tigl_nightly: "ON"
#          tigl_concat_generated_files: "ON"
#          tigl_enable_coverage: 'OFF'
#          build-artifact: build-macOS-10.15-Release-nightly-ON-concat-ON-cov-OFF-static-ON-python-OFF

#  test-macos:
#    needs: build-macos
#    runs-on: "macOS-10.15"
#    steps:
#      - uses: actions/checkout@v2
#      - uses: ./.github/actions/test-macos
#        with:
#          build-artifact: build-macOS-10.15-Release-nightly-ON-concat-ON-cov-OFF-static-ON-python-OFF
#          coverage: false
#          unit-tests: true
#          integration-tests: false

#  deploy-macos:
#    needs: test-macos
#    runs-on: "macOS-10.15"
#    steps:
#      - uses: actions/checkout@v2
#      - uses: ./.github/actions/deploy-macos
#        with:
#          build-artifact: build-macOS-10.15-Release-nightly-ON-concat-ON-cov-OFF-static-ON-python-OFF
#          documentation: false
